version:  '3.8'

services:

  mongodb:
    image: "mongo:latest"
    networks:
      - nosql
    ports:
      - 27017:27017

  couchdb:
    image: "couchdb:latest"
    networks:
      - nosql
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password


networks:
  nosql: